pipeline:
  processID: Juno clustering
  tag: first_run_runsheet
  projectID: myco
  lsf_queue: bio-prio-acc
  name: "myco_clustering"
  type: input_list
  full_path: true
  dataobjects:
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/consensus/NLA002300442.fasta
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/seq_exp_json/NLA002300442.json
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/consensus/NLA002300531.fasta
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/seq_exp_json/NLA002300531.json
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/consensus/NLA002300543.fasta
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/seq_exp_json/NLA002300543.json
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/consensus/NLA002300546.fasta
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/seq_exp_json/NLA002300546.json
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/consensus/NLA002300547.fasta
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/seq_exp_json/NLA002300547.json
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/consensus/NLA002300548.fasta
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/seq_exp_json/NLA002300548.json
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/consensus/NLA002300549.fasta
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/seq_exp_json/NLA002300549.json
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/consensus/NLA002300550.fasta
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/seq_exp_json/NLA002300550.json
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/consensus/NLA002300552.fasta
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/seq_exp_json/NLA002300552.json
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/consensus/NLA002300554.fasta
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/seq_exp_json/NLA002300554.json
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/consensus/NLA002300555.fasta
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/seq_exp_json/NLA002300555.json
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/consensus/NLZ002305088.fasta
    - /rivmZone_acc_01/projects/myco/230906_NB502001_0031_AH2TM7BGXV_0064/mtb_typing/seq_exp_json/NLZ002305088.json
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/consensus/NLA002300614.fasta
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/seq_exp_json/NLA002300614.json
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/consensus/NLA002300694.fasta
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/seq_exp_json/NLA002300694.json
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/consensus/NLA002300724.fasta
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/seq_exp_json/NLA002300724.json
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/consensus/NLA002300725.fasta
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/seq_exp_json/NLA002300725.json
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/consensus/NLA002300726.fasta
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/seq_exp_json/NLA002300726.json
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/consensus/NLA002300727.fasta
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/seq_exp_json/NLA002300727.json
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/consensus/NLA002300728.fasta
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/seq_exp_json/NLA002300728.json
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/consensus/NLA002300729.fasta
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/seq_exp_json/NLA002300729.json
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/consensus/NLA002300730.fasta
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/seq_exp_json/NLA002300730.json
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/consensus/NLA002300731.fasta
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/seq_exp_json/NLA002300731.json
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/consensus/NLA002300732.fasta
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/seq_exp_json/NLA002300732.json
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/consensus/NLA002300733.fasta
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/seq_exp_json/NLA002300733.json
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/consensus/NLA002300734.fasta
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/seq_exp_json/NLA002300734.json
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/consensus/NLA002300735.fasta
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/seq_exp_json/NLA002300735.json
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/consensus/NLA002300736.fasta
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/seq_exp_json/NLA002300736.json
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/consensus/NLA002300737.fasta
    - /rivmZone_acc_01/projects/myco/231229_VH01799_2_AAFGKWKM5_0086/mtb_typing/seq_exp_json/NLA002300737.json
    - /rivmZone_acc_01/projects/myco/myco_test_01_0005/mtb_typing/consensus/NLA001800072.fasta
    - /rivmZone_acc_01/projects/myco/myco_test_01_0005/mtb_typing/seq_exp_json/NLA001800072.json
    - /rivmZone_acc_01/projects/myco/myco_test_01_0005/mtb_typing/consensus/NLA001800078.fasta
    - /rivmZone_acc_01/projects/myco/myco_test_01_0005/mtb_typing/seq_exp_json/NLA001800078.json
    - /rivmZone_acc_01/projects/myco/myco_test_01_0005/mtb_typing/consensus/NLA001800079.fasta
    - /rivmZone_acc_01/projects/myco/myco_test_01_0005/mtb_typing/seq_exp_json/NLA001800079.json
    - /rivmZone_acc_01/projects/myco/myco_test_01_0005/mtb_typing/consensus/NLA001800085.fasta
    - /rivmZone_acc_01/projects/myco/myco_test_01_0005/mtb_typing/seq_exp_json/NLA001800085.json
    - /rivmZone_acc_01/projects/myco/myco_test_02_0002/mtb_typing/consensus/NLA001800090.fasta
    - /rivmZone_acc_01/projects/myco/myco_test_02_0002/mtb_typing/seq_exp_json/NLA001800090.json
    - /rivmZone_acc_01/projects/myco/myco_test_02_0002/mtb_typing/consensus/NLA001800127.fasta
    - /rivmZone_acc_01/projects/myco/myco_test_02_0002/mtb_typing/seq_exp_json/NLA001800127.json
    - /rivmZone_acc_01/projects/myco/myco_test_02_0002/mtb_typing/consensus/NLA001800143.fasta
    - /rivmZone_acc_01/projects/myco/myco_test_02_0002/mtb_typing/seq_exp_json/NLA001800143.json
    - /rivmZone_acc_01/projects/myco/myco_test_03_0002/mtb_typing/consensus/NLA001600850.fasta
    - /rivmZone_acc_01/projects/myco/myco_test_03_0002/mtb_typing/seq_exp_json/NLA001600850.json
    - /rivmZone_acc_01/projects/myco/myco_test_03_0002/mtb_typing/consensus/NLA001800276.fasta
    - /rivmZone_acc_01/projects/myco/myco_test_03_0002/mtb_typing/seq_exp_json/NLA001800276.json
    - /rivmZone_acc_01/projects/myco/myco_test_03_0002/mtb_typing/consensus/NLA001800279.fasta
    - /rivmZone_acc_01/projects/myco/myco_test_03_0002/mtb_typing/seq_exp_json/NLA001800279.json
    - /rivmZone_acc_01/projects/myco/myco_test_03_0002/mtb_typing/consensus/NLA001800280.fasta
    - /rivmZone_acc_01/projects/myco/myco_test_03_0002/mtb_typing/seq_exp_json/NLA001800280.json
    - /rivmZone_acc_01/projects/myco/myco_test_03_0002/mtb_typing/consensus/NLA001800290.fasta
    - /rivmZone_acc_01/projects/myco/myco_test_03_0002/mtb_typing/seq_exp_json/NLA001800290.json
