__package_name__ = "juno_clustering"
__authors__ = "Boas van der Putten, Roxanne Wolthuis, Sohana Singh"
__email__ = "ids-bioinformatics@rivm.nl"
__license__ = "AGPLv3"
__version__ = "0.0.1"
__description__ = "Juno-clustering pipeline for iterative clustering of SNP or cg/wgMLST data."
